dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        - docker build -f Dockerfile.alpine -t opencv-docker-golang:alpine -t opencv-docker-golang:latest .
        - docker images
        - docker tag opencv-docker-golang $DOCKERHUB_USERNAME/opencv-docker-golang
        - docker push $DOCKERHUB_USERNAME/opencv-docker-golang
