name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Build the Docker image with golang:buster
      #   run: docker build . --file Dockerfile.buster --tag opencv-docker-golang:buster

      - name: Build the Docker image with ubuntu:20.04
        run: docker build . --file Dockerfile.ubuntu --tag opencv-docker-golang:ubuntu

      # - name: Build the Docker image with dlib
      #   run: docker build . --file Dockerfile.dlib --tag opencv-docker-golang:dlib
  push_to_registries:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Push Docker image to multiple registries
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          build-args: |
            -f=Dockerfile.ubuntu
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
